# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E5VSU8Ttig9Nmt8hGVZF-R7awbFM7N6C
"""

from google.colab import drive
drive.mount('/content/drive')
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer
import math
import copy
import os
import random
from pathlib import Path
import re
import string
from collections import Counter
import matplotlib.pyplot as plt
import seaborn as sns
from IPython import display
from matplotlib_inline import backend_inline

class MultiheadAttention(nn.Module):
  def __init__(self, model_dim, num_heads, dropout = 0.1):
    super().__init__()
    assert model_dim % num_heads == 0, "d_model 必须能被 num_heads 整除"
    self.model_dim = model_dim
    self.head_dim = model_dim // num_heads
    self.num_heads = num_heads
    self.Wq = nn.Linear(model_dim, model_dim, bias=False)
    self.Wk = nn.Linear(model_dim, model_dim, bias=False)
    self.Wv = nn.Linear(model_dim, model_dim, bias=False)
    self.Wo = nn.Linear(model_dim, model_dim, bias=False)
    self.dropout = nn.Dropout(dropout)

  def forward(self, query, key, value, mask = None):
    #N: (batch_size, seq_len, model_dim)
    N = query.shape[0]
    #Q,K,V: (batch_size, num_heads, seq_len, head_dim)
    Q = self.Wq(query).view(N,-1,self.num_heads,self.head_dim).transpose(1,2)
    K = self.Wk(key).view(N,-1,self.num_heads,self.head_dim).transpose(1,2)
    V = self.Wv(value).view(N,-1,self.num_heads,self.head_dim).transpose(1,2)
    #scores: (batch_size, num_head, seq_len, seq_len)
    scores = torch.matmul(Q, K.transpose(-1,-2))/math.sqrt(self.head_dim)
    if mask is not None:
      #mask: (1,1,seq_len,seq_len)
      scores = scores.masked_fill(mask == 1, -1e8)
    #attention_weights: (batch_size, num_head, seq_len, seq_len)
    attention_weights = torch.softmax(scores, dim = -1)
    attention_weights = self.dropout(attention_weights)
    #context: (batch_size, num_heads, seq_len, head_dim)
    context = torch.matmul(attention_weights,V)
    context = context.transpose(1,2).contiguous().view(N,-1,self.model_dim)
    output = self.Wo(context)
    return output

class TransformerEncoderLayer(nn.Module):
  def __init__(self, model_dim, num_heads, dropout = 0.1, dim_feedforward = None):
    super().__init__()
    self.attention = MultiheadAttention(model_dim, num_heads, dropout)
    dim_feedforward = dim_feedforward or (model_dim * 4)
    self.FF = nn.Sequential(
        nn.Linear(model_dim,dim_feedforward),
        nn.ReLU(),
        nn.Linear(dim_feedforward,model_dim)
    )
    self.layer_norm1 = nn.LayerNorm(model_dim)
    self.layer_norm2 = nn.LayerNorm(model_dim)
    self.dropout = nn.Dropout(dropout)

  def forward(self,X,mask=None):
    attn_out = self.attention(X,X,X,mask=mask)
    o1 = self.layer_norm1(X + self.dropout(attn_out))
    ff_out = self.FF(o1)
    o2 = self.layer_norm2(o1 + self.dropout(ff_out))
    return o2

class TransformerEncoder(nn.Module):
  def __init__(self, encoder_layer, num_encoders = 6):
    super().__init__()
    self.layers = nn.ModuleList([copy.deepcopy(encoder_layer) for _ in range(num_encoders)])
    model_dim = encoder_layer.layer_norm1.normalized_shape[0]
    self.norm = nn.LayerNorm(model_dim)

  def forward(self, X, mask = None):
    output = X
    for layer in self.layers:
      output = layer(output,mask)
    output = self.norm(output)
    return output

class TransformerDecoderLayer(nn.Module):
  def __init__(self, model_dim, num_heads, dropout = 0.1, dim_feedforward = None):
    super().__init__()
    self.attention1 = MultiheadAttention(model_dim, num_heads, dropout)
    self.attention2 = MultiheadAttention(model_dim, num_heads, dropout)
    dim_feedforward = dim_feedforward or (model_dim * 4)
    self.FF = nn.Sequential(
        nn.Linear(model_dim,dim_feedforward),
        nn.ReLU(),
        nn.Linear(dim_feedforward,model_dim)
    )
    self.layer_norm1 = nn.LayerNorm(model_dim)
    self.layer_norm2 = nn.LayerNorm(model_dim)
    self.layer_norm3 = nn.LayerNorm(model_dim)
    self.dropout = nn.Dropout(dropout)

  def forward(self,tgt,Encoder_output,tgt_mask=None,memory_mask=None):
    attn_out1 = self.attention1(tgt,tgt,tgt,mask=tgt_mask)
    o1 = self.layer_norm1(tgt + self.dropout(attn_out1))
    attn_out2 = self.attention2(o1,Encoder_output,Encoder_output,mask=memory_mask)
    o2 = self.layer_norm2(o1 + self.dropout(attn_out2))
    ff_out = self.FF(o2)
    o3 = self.layer_norm3(o2 + self.dropout(ff_out))
    return o3

class TransformerDecoder(nn.Module):
  def __init__(self, decoder_layer, num_decoders = 6):
    super().__init__()
    self.layers = nn.ModuleList([copy.deepcopy(decoder_layer) for _ in range(num_decoders)])
    model_dim = decoder_layer.layer_norm1.normalized_shape[0]
    self.norm = nn.LayerNorm(model_dim)

  def forward(self, tgt, Encoder_output,tgt_mask=None,memory_mask=None):
    output = tgt
    for layer in self.layers:
      output = layer(output, Encoder_output, tgt_mask=tgt_mask, memory_mask=memory_mask)
    output = self.norm(output)
    return output

class Transformer(nn.Module):
  def __init__(self, TransformerEncoder, TransformerDecoder, embed_layer, model_dim, vocab_size, pad_id, max_seq_len=50):
      super().__init__()
      self.pad_id = pad_id
      self.embedding = embed_layer
      self.pos_embedding = nn.Embedding(max_seq_len, model_dim)
      self.encoder = TransformerEncoder
      self.decoder = TransformerDecoder
      self.linear = nn.Linear(model_dim,vocab_size)

  def forward(self, src, tgt_input):
    N, seq_len_x = src.shape
    _, seq_len_tgt = tgt_input.shape
    device = src.device
    # (N, seq_len_x) 扩充为 (N, 1, 1, seq_len_x)
    encoder_mask = (src == self.pad_id).unsqueeze(1).unsqueeze(2)

    causal_mask = torch.triu(torch.ones(seq_len_tgt, seq_len_tgt, dtype=torch.bool, device=device), diagonal=1)
    causal_mask = causal_mask.unsqueeze(0).unsqueeze(0)

    tgt_pad_mask = (tgt_input == self.pad_id).unsqueeze(1).unsqueeze(2) # (N, 1, 1, seq_len_tgt)

    tgt_mask = causal_mask | tgt_pad_mask

    memory_mask = encoder_mask

    position_x = torch.arange(0, seq_len_x, device=device).unsqueeze(0).expand(N, seq_len_x)
    position_tgt = torch.arange(0, seq_len_tgt, device=device).unsqueeze(0).expand(N, seq_len_tgt)

    X_emb = self.embedding(src) + self.pos_embedding(position_x)
    tgt_emb = self.embedding(tgt_input) + self.pos_embedding(position_tgt)

    encoder_output = self.encoder(X_emb, mask=encoder_mask)
    decoder_output = self.decoder(tgt_emb, encoder_output, tgt_mask=tgt_mask, memory_mask=memory_mask)
    output = self.linear(decoder_output)

    return output

  @torch.no_grad()
  def generate(self, src, bgn_id, max_len):
    self.eval()
    batch_size = src.size(0)
    current_input = torch.full((batch_size, 1), bgn_id, dtype=torch.long, device=src.device)
    for _ in range(max_len):
      prediction = self.forward(src=src,tgt_input = current_input)
      next_token = torch.argmax(prediction[:,-1,:],dim=-1,keepdim=True)
      current_input = torch.cat([current_input,next_token],dim=1)
    return current_input

  def _init_weights(self):
    for p in self.parameters():
      if p.dim()>1:
        nn.init.xavier_uniform_(p)

class DecoderOnlyTransformerLayer(nn.Module):
  def __init__(self,model_dim, num_heads, dropout = 0.1, dim_feedforward = None):
    super().__init__()
    self.attention = MultiheadAttention(model_dim, num_heads, dropout)
    dim_feedforward = dim_feedforward or (model_dim*4)
    self.FF = nn.Sequential(
        nn.Linear(model_dim, dim_feedforward),
        nn.ReLU(),
        nn.Linear(dim_feedforward, model_dim)
    )
    self.layer_norm1 = nn.LayerNorm(model_dim)
    self.layer_norm2 = nn.LayerNorm(model_dim)
    self.dropout = nn.Dropout(dropout)

  def forward(self,data,mask = None):
    attn_o1 = self.attention(data,data,data,mask = mask)
    o1 = self.layer_norm1(data + self.dropout(attn_o1))
    FF_output = self.FF(o1)
    o2 = self.layer_norm2(o1 + self.dropout(FF_output))
    return o2

class DecoderOnlyTransformer(nn.Module):
    def __init__(self, DecoderOnlyTransformerLayer, embed_layer, model_dim, vocab_size, pad_id, layer_num=2, max_seq_len=512):
        super().__init__()
        self.pad_id = pad_id
        self.embedding = embed_layer
        self.pos_embedding = nn.Embedding(max_seq_len, model_dim)
        self.decoders = nn.ModuleList([copy.deepcopy(DecoderOnlyTransformerLayer) for _ in range(layer_num)])
        self.linear = nn.Linear(model_dim, vocab_size)

    def forward(self, x, mask=None):
        N, seq_len = x.shape
        device = x.device
        causal_mask = torch.triu(torch.ones(seq_len, seq_len, dtype=torch.bool, device=device), diagonal=1)
        causal_mask = causal_mask.unsqueeze(0).unsqueeze(0)
        pad_mask = (x == self.pad_id).unsqueeze(1).unsqueeze(2)
        mask = causal_mask | pad_mask

        pos_encoding = torch.arange(0, seq_len, device=device).unsqueeze(0).expand(N, seq_len)
        output = self.embedding(x) + self.pos_embedding(pos_encoding)
        for decoder in self.decoders:
            output = decoder(output, mask=mask)
        return self.linear(output)

    @torch.no_grad()
    def generate(self,x,max_len):
        self.eval()
        current_input = x
        for _ in range(max_len):
            # 动态截取，防止自回归生成的长度超过位置编码支持的最大长度
            max_seq = self.pos_embedding.num_embeddings
            context = current_input[:, -max_seq:] if current_input.size(1) > max_seq else current_input
            prediction = self.forward(context)
            next_token = torch.argmax(prediction[:, -1, :], dim=-1, keepdim=True)
            current_input = torch.cat([current_input, next_token], dim=1)
        return current_input

    def _init_weights(self):
        for p in self.parameters():
            if p.dim() > 1:
                nn.init.xavier_uniform_(p)

class metrics_accumulator:
    def __init__(self, n):
        self.metrics = [0.0]*n

    def add(self,*args):
        self.metrics = [a + float(b) for a,b in zip(self.metrics, args)]

    def reset(self):
        self.metrics = [0.0] * len(self.metrics)

    def get_item(self, idx):
        return self.metrics[idx]

class Animator:
    def __init__(self, task_type='SubTask_1', figsize=(6, 4)):
        # 根据任务自动调整坐标轴标签和图例
        if task_type == 'SubTask_1':
            self.legend_labels = ['Train Loss', 'Train Exact Match', 'Dev Loss', 'Dev Exact Match']
            self.y2_label = 'Exact Match Rate'
        else:
            self.legend_labels = ['Train Loss', 'Train PPL', 'Dev Loss', 'Dev PPL']
            self.y2_label = 'Perplexity (PPL)'

        plt.style.use('default')
        plt.rcParams['font.family'] = 'serif'
        plt.rcParams['font.serif'] = ['Times New Roman'] + plt.rcParams['font.serif']
        plt.rcParams['figure.dpi'] = 300

        backend_inline.set_matplotlib_formats("svg")
        self.fig, self.ax1 = plt.subplots(figsize=figsize)
        self.ax2 = self.ax1.twinx()

        self.line_styles = [
            {'color': '#1f77b4', 'linestyle': '-',  'linewidth': 1.5},
            {'color': '#d62728', 'linestyle': '-',  'linewidth': 1.5},
            {'color': '#1f77b4', 'linestyle': '--', 'linewidth': 1.5},
            {'color': '#d62728', 'linestyle': '--', 'linewidth': 1.5}
        ]

        def config_axes():
            self.ax1.set_xlabel('Epoch', fontsize=11)
            self.ax2.yaxis.tick_right()
            self.ax2.yaxis.set_label_position("right")

            self.ax1.set_ylabel('Cross Entropy Loss', fontsize=11, color='#1f77b4')
            self.ax2.set_ylabel(self.y2_label, fontsize=11, color='#d62728')

            self.ax1.tick_params(axis='y', labelcolor='#1f77b4')
            self.ax2.tick_params(axis='y', labelcolor='#d62728')

            self.ax1.spines['top'].set_visible(False)
            self.ax2.spines['top'].set_visible(False)
            self.ax1.spines['left'].set_color('#1f77b4')
            self.ax2.spines['right'].set_color('#d62728')
            self.ax1.grid(True, linestyle='--', alpha=0.5, zorder=0)

        self.config_axes = config_axes
        self.X, self.Y = None, None

    def add(self, x, y):
        if not hasattr(y, "__len__"): y = [y]
        n = len(y)
        if not hasattr(x, "__len__"): x = [x] * n
        if not self.X: self.X = [[] for _ in range(n)]
        if not self.Y: self.Y = [[] for _ in range(n)]

        for i, (a, b) in enumerate(zip(x, y)):
            if a is not None and b is not None:
                self.X[i].append(a)
                self.Y[i].append(b)

        self.ax1.cla()
        self.ax2.cla()

        lines = []
        for i, (x_data, y_data) in enumerate(zip(self.X, self.Y)):
            style = self.line_styles[i % len(self.line_styles)]
            if i % 2 == 0:
                line, = self.ax1.plot(x_data, y_data, **style, zorder=3)
            else:
                line, = self.ax2.plot(x_data, y_data, **style, zorder=3)
            lines.append(line)

        self.config_axes()
        if self.legend_labels:
            self.ax1.legend(lines, self.legend_labels, frameon=False,
                            fontsize=9, loc='center right', bbox_to_anchor=(0.95, 0.5))

        plt.tight_layout()
        display.display(self.fig)
        display.clear_output(wait=True)

    def save_fig(self, filename):
        self.fig.savefig(filename, format='pdf', bbox_inches='tight')

def calc_exact_match(y_hat, y, pad_id):
    # y_hat: (B, Seq, Vocab), y: (B, Seq)
    pred_seq = torch.argmax(y_hat, dim=-1)
    # 忽略 padding 位置，非 padding 位置必须完全一致
    mask = (y != pad_id)
    # 预测正确 或 该位置是 padding (不纳入错误考核)
    correct_tokens = (pred_seq == y) | (~mask)
    # dim=-1 代表对整个序列的所有 token 求与(AND)操作
    exact_match = correct_tokens.all(dim=-1)
    return exact_match.sum().item(), y.size(0)

def build_model(config):
    embed_layer = build_embedding_layer(config)

    if config['model_type'] == "transformer":
        encoder_layer = TransformerEncoderLayer(config['model_dim'], config['num_heads'], config['dropout'], dim_feedforward=config['dim_feedforward'])
        encoder = TransformerEncoder(encoder_layer, config['num_encoders'])
        decoder_layer = TransformerDecoderLayer(config['model_dim'], config['num_heads'], config['dropout'], dim_feedforward=config['dim_feedforward'])
        decoder = TransformerDecoder(decoder_layer, config['num_decoders'])
        model = Transformer(encoder, decoder, embed_layer, config['model_dim'], config['vocab_size'], config['pad_id'], max_seq_len=config['max_seq_len'])
        model._init_weights()
        return model

    elif config['model_type'] == "decoder":
        layer = DecoderOnlyTransformerLayer(config['model_dim'], config['num_heads'], config['dropout'], dim_feedforward=config['dim_feedforward'])
        model = DecoderOnlyTransformer(layer, embed_layer, config['model_dim'], config['vocab_size'], config['pad_id'], config['layer_num'], max_seq_len=config.get('max_seq_len', 512))
        model._init_weights()
        return model
    else:
        raise ValueError("不支持的模型类型")

def build_optimizer(model, config):
  trainable_params = filter(lambda p: p.requires_grad, model.parameters())
  if config['optimizer'] == 'Adam':
      return torch.optim.Adam(trainable_params, lr=config['lr'])
  elif config['optimizer'] == 'Adadelta':
      return torch.optim.Adadelta(trainable_params, lr=config['lr'])
  elif config['optimizer'] == 'SGD':
      return torch.optim.SGD(trainable_params, lr=config['lr'], momentum=0.9)

class UniversalTrainer:
    def __init__(self, config, device, metrics_accumulator):
        self.config = config
        self.model = build_model(config).to(device)
        self.optimizer = build_optimizer(self.model, config)
        self.criterion = nn.CrossEntropyLoss(ignore_index=config['pad_id'])
        self.scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(self.optimizer, mode='min', factor=0.5, patience=3)

        self.device = device
        self.metrics = metrics_accumulator
        self.animator = Animator(task_type=config['task'])
        self.best_dev_loss = float('inf')
        self.patience_counter = 0
        self.history = []

    def train_and_evaluate(self, num_epochs, train_dataloader, dev_dataloader):
        global_step = 0
        observe_steps = [10, 100, 500, 1000, 3000, 5000, 10000]
        fixed_prompt = "Ross: Hey guys! "

        for epoch in range(num_epochs):
            self.model.train()
            self.metrics.reset()

            for batch in train_dataloader:
                global_step += 1 # 记录全局训练步数
                inputs, labels = batch
                inputs = {k: v.to(self.device) for k, v in inputs.items()}
                labels = labels.to(self.device)

                self.optimizer.zero_grad()
                outputs = self.model(**inputs)
                train_loss = self.criterion(outputs.view(-1, outputs.size(-1)), labels.view(-1))
                train_loss.backward()
                self.optimizer.step()

                if self.config['task'] == 'SubTask_1':
                    num_correct, batch_size = calc_exact_match(outputs, labels, self.config['pad_id'])
                    self.metrics.add(train_loss.item() * batch_size, num_correct, batch_size, 0, 0, 0)
                else:
                    valid_tokens = (labels != self.config['pad_id']).sum().item()
                    self.metrics.add(train_loss.item() * valid_tokens, 0, valid_tokens, 0, 0, 0)

                # 基于 Step 的文本生成观测钩子
                if self.config['task'] == 'SubTask_2' and global_step in observe_steps:
                    print(f"\n[{'='*15} Global Step: {global_step} (Epoch {epoch+1}) {'='*15}]")
                    # 临时切换到评估模式以关闭 Dropout
                    self.model.eval()
                    sample_text = generate_lm_text(self.model, self.config, prompt_text=fixed_prompt, max_new_tokens=100)
                    print(f"Prompt: {fixed_prompt}")
                    print(f"Output: {sample_text}\n")
                    # 观测完毕，切回训练模式继续学习
                    self.model.train()

            self.model.eval()
            with torch.no_grad():
                for batch in dev_dataloader:
                    dev_inputs, dev_labels = batch
                    dev_inputs = {k: v.to(self.device) for k, v in dev_inputs.items()}
                    dev_labels = dev_labels.to(self.device)

                    dev_outputs = self.model(**dev_inputs)
                    dev_loss = self.criterion(dev_outputs.view(-1, dev_outputs.size(-1)), dev_labels.view(-1))

                    if self.config['task'] == 'SubTask_1':
                        num_correct, batch_size = calc_exact_match(dev_outputs, dev_labels, self.config['pad_id'])
                        self.metrics.add(0, 0, 0, dev_loss.item() * batch_size, num_correct, batch_size)
                    else:
                        valid_tokens = (dev_labels != self.config['pad_id']).sum().item()
                        self.metrics.add(0, 0, 0, dev_loss.item() * valid_tokens, 0, valid_tokens)

            train_loss_avg = self.metrics.get_item(0) / self.metrics.get_item(2)
            dev_loss_avg = self.metrics.get_item(3) / self.metrics.get_item(5)

            if self.config['task'] == 'SubTask_1':
                train_metric = self.metrics.get_item(1) / self.metrics.get_item(2)
                dev_metric = self.metrics.get_item(4) / self.metrics.get_item(5)
            else:
                train_metric = math.exp(min(train_loss_avg, 20))
                dev_metric = math.exp(min(dev_loss_avg, 20))

            self.animator.add(epoch + 1, (train_loss_avg, train_metric, dev_loss_avg, dev_metric))
            self.scheduler.step(dev_loss_avg)

            metric_name = 'Exact_Match' if self.config['task'] == 'SubTask_1' else 'Perplexity'
            self.history.append({
                'Epoch': epoch + 1,
                'Train_Loss': train_loss_avg,
                f'Train_{metric_name}': train_metric,
                'Dev_Loss': dev_loss_avg,
                f'Dev_{metric_name}': dev_metric
            })

            if dev_loss_avg < self.best_dev_loss:
                self.best_dev_loss = dev_loss_avg
                best_state_dict = copy.deepcopy(self.model.state_dict())
                self.patience_counter = 0
            else:
                self.patience_counter += 1

            if self.patience_counter >= self.config['patience']:
                print(f"在第 {epoch+1} 轮触发早停")
                break

        pic_save_path = f"/content/drive/MyDrive/pytorch_beginner/task3/{self.config['exp_name']}_curve.pdf"
        self.animator.save_fig(pic_save_path)
        self.save_metrics_to_file()

        return self.best_dev_loss, best_state_dict

    def save_metrics_to_file(self):
        if not self.history:
            return

        df = pd.DataFrame(self.history)

        save_path = f"/content/drive/MyDrive/pytorch_beginner/task3/{self.config['exp_name']}_metrics.csv"
        df.to_csv(save_path, index=False, encoding='utf-8-sig')
        print(f"[*] 训练指标表格已保存至: {save_path}")

    def test(self, test_dataloader, config):
        self.model.eval()
        total_correct = 0
        total_samples = 0
        total_loss = 0.0
        total_tokens = 0

        with torch.no_grad():
            for batch in test_dataloader:
                inputs, labels = batch
                inputs = {k: v.to(self.device) for k, v in inputs.items()}
                labels = labels.to(self.device)

                if config['task'] == 'SubTask_1':
                    bgn_id = config['bgn_id']
                    end_id = config.get('end_id', 2)

                    if config['model_type'] == 'transformer':
                        predictions = self.model.generate(inputs['src'], bgn_id, config['max_gen_len'])
                        predictions = predictions[:, 1:] # 去掉前导 BOS

                        for i in range(labels.size(0)):
                            pred_seq = predictions[i].tolist()
                            true_seq = labels[i].tolist()

                            if end_id in pred_seq: pred_seq = pred_seq[:pred_seq.index(end_id)]
                            if end_id in true_seq: true_seq = true_seq[:true_seq.index(end_id)]
                            if pred_seq == true_seq: total_correct += 1
                            total_samples += 1

                    elif config['model_type'] == 'decoder':
                        # 纯解码器测试：获取提示长度
                        prompt = inputs['x']
                        prompt_len = prompt.size(1)

                        # 自回归生成
                        predictions = self.model.generate(prompt, config['max_gen_len'])

                        # 核心差异：只截取模型新生成的答案部分进行对比，剔除它照抄的 prompt
                        generated_seq = predictions[0, prompt_len:].tolist()
                        true_seq = labels[0].tolist()

                        if end_id in generated_seq: generated_seq = generated_seq[:generated_seq.index(end_id)]
                        if end_id in true_seq: true_seq = true_seq[:true_seq.index(end_id)]
                        if generated_seq == true_seq: total_correct += 1
                        total_samples += 1

                elif config['task'] == 'SubTask_2':
                    # 语言模型测试集：计算整体 PPL
                    outputs = self.model(**inputs)
                    loss = self.criterion(outputs.view(-1, outputs.size(-1)), labels.view(-1))
                    valid_tokens = (labels != config['pad_id']).sum().item()
                    total_loss += loss.item() * valid_tokens
                    total_tokens += valid_tokens

        if config['task'] == 'SubTask_1':
            accuracy = (total_correct / total_samples) * 100 if total_samples > 0 else 0
            print(f"[{config['task']}] 测试集精确匹配率 (Exact Match): {accuracy:.2f}%")
            return accuracy
        else:
            avg_loss = total_loss / total_tokens if total_tokens > 0 else float('inf')
            ppl = math.exp(min(avg_loss, 20))
            print(f"[{config['task']}] 测试集困惑度 (Perplexity): {ppl:.4f}")
            return ppl

"""## 子任务1：自行构造数据让模型学习 3+3/3+4/4+3/3+5/5+3/4+4 等的多位数加法（"3+3" 指3位数+3位数）"""

def generate_addition_samples(digit_configs = [(3,3),(3,4),(4,3),(3,5),(5,3),(4,4)], num_examples = 10000):
  dataset = []
  for _ in range(num_examples):
    len_a, len_b = random.choice(digit_configs)
    a = random.randint(10**(len_a-1),10**len_a-1)
    b = random.randint(10**(len_b-1),10**len_b-1)
    equation = f"{a}+{b}="
    result = str(a+b)
    dataset.append({"X":equation,"y":result})
  dataset_df = pd.DataFrame(dataset)
  # 目标序列反转 (预测顺序：个位 -> 十位 -> 百位)
  dataset_df['y'] = dataset_df['y'].apply(lambda x: str(x)[::-1])
  return dataset_df

digits = ["<pad>","<bos>","<eos>","1","2","3","4","5","6","7","8","9","0","+","="]
char2id = {c: i for i, c in enumerate(digits)}
id2char = {i:c for i,c in enumerate(digits)}

def equation_tokenize(equation_dataset: pd.Series, add_bos = False, add_eos = False):
  bgn_id = char2id['<bos>']
  pad_id = char2id['<pad>']
  end_id = char2id['<eos>']
  tokenized_data = []
  for equation in equation_dataset:
    seq = [char2id[c] for c in str(equation)]
    if add_bos:
      seq = [bgn_id] + seq
    if add_eos:
      seq = seq + [end_id]
    tokenized_data.append(seq)
  max_length = max(len(seq) for seq in tokenized_data)
  padded_data = []
  for seq in tokenized_data:
    padded_data.append(seq + [pad_id]*(max_length-len(seq)))
  return torch.tensor(padded_data, dtype=torch.long)

def calc_accuracy(y_hat, y, pad_id):
    label_predict = torch.max(y_hat, dim=-1).indices
    # 创建掩码，忽略 pad_id
    mask = (y != pad_id)
    correct_predict = (label_predict == y) & mask
    num_correct = correct_predict.sum().item()
    # 注意：这里的基数也应该是 mask.sum().item()，而不是 batch_size
    # 但为了适配你现有的 metrics.add，返回值需要分离
    return num_correct, mask.sum().item()

class EquationDataset(Dataset):
  def __init__(self,X_data:pd.Series,y_data:pd.Series):
    self.src = equation_tokenize(X_data)
    self.tgt_input = equation_tokenize(y_data, add_bos = True)
    self.tgt_label = equation_tokenize(y_data, add_eos = True)

  def __len__(self):
    return len(self.src)

  def __getitem__(self,idx):
    inputs = {
        "src":self.src[idx],
        "tgt_input":self.tgt_input[idx],
        }
    return inputs, self.tgt_label[idx]

class DecoderEquationDataset(Dataset):
    def __init__(self, X_data: pd.Series, y_data: pd.Series, config, is_test=False):
        self.pad_id = config['pad_id']
        self.bgn_id = config['bgn_id']
        self.end_id = config.get('end_id', 2)
        self.is_test = is_test
        self.data = []

        for x_str, y_str in zip(X_data, y_data):
            # 提示部分：<BOS> 1 2 3 + 4 5 =
            prompt = [self.bgn_id] + [char2id[c] for c in str(x_str)]
            # 答案部分：5 7 1 <EOS>
            answer = [char2id[c] for c in str(y_str)] + [self.end_id]

            if not is_test:
                prompt_len = len(prompt)
                seq = prompt + answer

                # 输入 x 是 seq 的前 N-1 个 token
                x = seq[:-1]

                # === 核心修复：Prompt 掩码 (Prompt Masking) ===
                # 我们让 y 的前 prompt_len - 1 个位置全部变成 pad_id
                # 这样模型在预测题目部分时，Loss 会被 ignore_index 直接忽略
                y = [self.pad_id] * (prompt_len - 1) + answer

                max_len = config['max_seq_len']
                # 补齐 Padding
                if len(x) < max_len:
                    pad_len = max_len - len(x)
                    x += [self.pad_id] * pad_len
                    y += [self.pad_id] * pad_len

                self.data.append((x, y))
            else:
                # 测试模式：保留题目和纯净的答案，供逐条生成对比
                self.data.append((prompt, answer))

    def __len__(self): return len(self.data)

    def __getitem__(self, idx):
        inputs = {"x": torch.tensor(self.data[idx][0], dtype=torch.long)}
        labels = torch.tensor(self.data[idx][1], dtype=torch.long)
        return inputs, labels

"""## 子任务2：自行构造数据让模型学习一个语言模型（自己准备一个语料集）"""

def generate_corpus(folder = Path("/content/drive/MyDrive/pytorch_beginner/task3/friends_series_script")):

  scene_indicator = re.compile(r"^\[Scene.*\]$",re.MULTILINE)
  names = re.compile(r"^[A-Z][a-zA-Z\s]+:",re.MULTILINE)
  upper_case = list(range(100))

  #数据清洗
  data = []
  val_data = []
  for item in folder.iterdir():
    if item.is_file():
      content = item.read_text(encoding = 'utf8', errors='ignore')
      scenes = scene_indicator.split(content)
      #去掉剧本结尾的'End'
      if scenes:
        last_scene = scenes[-1]
        if last_scene.endswith("End"):
          scenes[-1] = last_scene.rsplit("\n",1)[0]
      #场景分离
      for s in scenes[1:]:
        scene = s.strip()
        if not scene:
          continue
        """#角色脱敏
        scene_characters_raw = set(names.findall(scene))
        scene_characters = {name.replace(":","").strip() for name in scene_characters_raw}
        if not scene_characters:
          continue
        name_mapping = {name:f"Speaker{upper_case[i]}" for i,name in enumerate(scene_characters)}
        sorted_names = sorted(scene_characters,key=len,reverse=True)
        pattern = re.compile(r"\b("+"|".join(re.escape(name) for name in sorted_names)+r")\b")
        anoymized_scene = pattern.sub(lambda m: name_mapping[m.group(0)],scene)"""
        #引入<\Action>包裹舞台提示
        scene = re.sub(r'\((.*?)\)', r'<ACTION> \1 </ACTION>', scene)
        #保留回车符以提示对话结束信息
        scene = re.sub(r'\n+','\n',scene)
        #引入边界符<EOS>
        scene = f"{scene} <EOS>"
        if torch.rand(1) < 0.1:
          val_data.append(scene)
        else:
          data.append(scene)
  friends_series_corpus = "\n".join(data)
  val_dataset = "\n".join(val_data)
  def safe_transform(corpus: str)->str:
      corpus = corpus.replace('\n', ' \n ')
      corpus = corpus.replace('<EOS>', ' <EOS> ')
      corpus = corpus.replace('<ACTION>', ' <ACTION> ')
      corpus = corpus.replace('</ACTION>', ' </ACTION> ')
      return corpus
  return safe_transform(friends_series_corpus), safe_transform(val_dataset)

def prepare_lm_data(config):
    safe_corpus, val_dataset = generate_corpus()
    words = safe_corpus.split()
    word_count = Counter(words)

    min_freq = config.get('min_freq', 2)
    valid_words = [w for w, count in word_count.items() if count >= min_freq]
    special_words = ["<pad>", "<unk>"]
    vocab = special_words + valid_words

    word2id = {word: i for i, word in enumerate(vocab)}
    unk_id = word2id["<unk>"]

    corpus_id = torch.tensor([word2id.get(word, unk_id) for word in words], dtype=torch.long)
    val_id = torch.tensor([word2id.get(word, unk_id) for word in val_dataset.split()], dtype=torch.long)

    return corpus_id, val_id, word2id

class friends_series_data(Dataset):
  def __init__(self, data, seq_len = 128, stride = 60):
    self.data = data
    self.seq_len = seq_len
    self.stride = stride
    self.indices = range(0,len(data)-seq_len,stride)

  def __len__(self):
    return len(self.indices)

  def __getitem__(self,idx):
    indice = self.indices[idx]
    batch_data = self.data[indice:(indice+self.seq_len)+1]
    inputs = {
        "x":batch_data[:-1]
    }
    return inputs, batch_data[1:]

@torch.no_grad()
def generate_lm_text(model, config, prompt_text, max_new_tokens=300, top_k=50, temperature=0.8):
    """自适应分词器的语言模型文本生成工具 (支持 Top-K 采样)"""
    model.eval()
    device = next(model.parameters()).device

    # 动态编码
    if config.get('tokenizer_type') == 'subword':
        tokenizer = config['tokenizer']
        input_ids = tokenizer.encode(prompt_text, return_tensors='pt').to(device)
    else:
        word2id = config['word2id']
        unk_id = word2id.get('<unk>', 1)
        # 简单切分匹配
        encoded = [word2id.get(w, unk_id) for w in prompt_text.split()]
        input_ids = torch.tensor([encoded], dtype=torch.long, device=device)

    # 自回归生成
    for _ in range(max_new_tokens):
        # 裁剪输入，防止超过最大序列长度导致位置编码越界
        max_seq = config.get('max_seq_len', 128)
        context_ids = input_ids[:, -max_seq:] if input_ids.size(1) > max_seq else input_ids

        outputs = model(context_ids)
        next_token_logits = outputs[:, -1, :] / temperature

        # Top-K 采样过滤 (替代之前的贪婪解码 argmax，缓解复读机现象)
        v, _ = torch.topk(next_token_logits, top_k)
        next_token_logits[next_token_logits < v[:, [-1]]] = -float('Inf')
        probs = torch.softmax(next_token_logits, dim=-1)
        next_token = torch.multinomial(probs, num_samples=1)

        input_ids = torch.cat([input_ids, next_token], dim=1)

    # 动态解码
    if config.get('tokenizer_type') == 'subword':
        return tokenizer.decode(input_ids[0].tolist(), skip_special_tokens=True)
    else:
        id2word = {v: k for k, v in config['word2id'].items()}
        return " ".join([id2word.get(idx, "<unk>") for idx in input_ids[0].tolist()])

def build_embedding_layer(config):
    vocab_size = config['vocab_size']
    model_dim = config['model_dim']
    pad_id = config['pad_id']

    # 逻辑解耦：如果是加法任务，或者明确配置不使用 GloVe，直接返回随机初始化层
    if config['task'] != 'SubTask_2' or not config.get('use_glove', False):
        return nn.Embedding(vocab_size, model_dim, padding_idx=pad_id)

    glove_path = config.get('glove_path', '')
    word2id = config.get('word2id', {})

    if not os.path.exists(glove_path) or not word2id:
        print("警告: 找不到 GloVe 路径或 word2id，回退到随机初始化。")
        return nn.Embedding(vocab_size, model_dim, padding_idx=pad_id)

    print(f"正在加载 GloVe 预训练词向量: {glove_path} ...")
    glove_vectors = {}
    with open(glove_path, "r", encoding="utf8") as f:
        for line in f:
            parts = line.split()
            # 兼容不同维度的预训练向量
            glove_vectors[parts[0]] = torch.tensor([float(x) for x in parts[1:]], dtype=torch.float32)

    embedding_matrix = torch.zeros(vocab_size, model_dim)
    hit_count = 0
    for word, idx in word2id.items():
        if word in glove_vectors:
            embedding_matrix[idx] = glove_vectors.get(word)
            hit_count += 1
        else:
            if word not in ['<unk>', '<pad>']:
                embedding_matrix[idx] = torch.randn(model_dim) * 0.1

    print(f"GloVe 命中率: {hit_count / vocab_size * 100:.2f}%")

    return nn.Embedding.from_pretrained(
        embeddings=embedding_matrix,
        freeze=config.get('freeze_embedding', False),
        padding_idx=pad_id
    )

def build_dataloaders(config):
    if config['task'] == 'SubTask_1':
        train_equation_dataset = generate_addition_samples(
            digit_configs=config['train_digit_configs'], num_examples=config['train_examples'])

        config['vocab_size'] = len(digits)
        config['pad_id'] = char2id['<pad>']
        config['bgn_id'] = char2id['<bos>']
        config['end_id'] = char2id['<eos>']

        X_train, X_dev, y_train, y_dev = train_test_split(
            train_equation_dataset['X'], train_equation_dataset['y'], test_size=0.2)

        if config['model_type'] == 'transformer':
            train_data = DataLoader(EquationDataset(X_train, y_train), batch_size=config['batch_size'], shuffle=True)
            dev_data = DataLoader(EquationDataset(X_dev, y_dev), batch_size=config['batch_size'], shuffle=False)
        elif config['model_type'] == 'decoder':
            train_data = DataLoader(DecoderEquationDataset(X_train, y_train, config), batch_size=config['batch_size'], shuffle=True)
            dev_data = DataLoader(DecoderEquationDataset(X_dev, y_dev, config), batch_size=config['batch_size'], shuffle=False)

        return train_data, dev_data

    elif config['task'] == 'SubTask_2':
        if config.get('tokenizer_type', 'word') == 'subword':
            print("[*] 正在加载 Subword Tokenizer (基于 GPT-2 BPE) ...")
            # 使用标准的 GPT2 BPE 分词器
            tokenizer = AutoTokenizer.from_pretrained("gpt2")
            tokenizer.pad_token = tokenizer.eos_token # GPT2默认无pad_token

            safe_corpus, val_dataset = generate_corpus()

            # 直接将整个文本编码为张量
            corpus_id = tokenizer.encode(safe_corpus, return_tensors='pt').squeeze(0)
            val_id = tokenizer.encode(val_dataset, return_tensors='pt').squeeze(0)

            config['vocab_size'] = tokenizer.vocab_size + len(tokenizer.get_added_vocab())
            config['pad_id'] = tokenizer.pad_token_id
            config['tokenizer'] = tokenizer # 保存实例供解码时使用

            # 强制关闭 GloVe，因为子词无法与 GloVe 字典直接对齐
            if config.get('use_glove', False):
                print("[!] 警告: 子词分词与 GloVe 冲突，已自动关闭 GloVe 加载。")
                config['use_glove'] = False

        else:
            corpus_id, val_id, word2id = prepare_lm_data(config)
            config['vocab_size'] = len(word2id)
            config['pad_id'] = word2id['<pad>']
            config['word2id'] = word2id

        SEQ_LEN = config.get('max_seq_len', 128)
        STRIDE = config.get('stride', 64)
        BATCH_SIZE = config['batch_size']

        friends_dataset_train = friends_series_data(corpus_id, seq_len=SEQ_LEN, stride=STRIDE)
        friends_dataset_eval = friends_series_data(val_id, seq_len=SEQ_LEN, stride=SEQ_LEN)

        train_data = DataLoader(friends_dataset_train, batch_size=BATCH_SIZE, shuffle=True, drop_last=True)
        dev_data = DataLoader(friends_dataset_eval, batch_size=BATCH_SIZE, drop_last=True)

        return train_data, dev_data

    else:
        raise ValueError(f"未知的任务类型: {config['task']}")

def build_test_dataloader(config):
    if config['task'] == 'SubTask_1':
        test_equation_dataset = generate_addition_samples(
            digit_configs=config['test_digit_configs'], num_examples=config['test_examples'])

        # === 核心调度分支 ===
        if config['model_type'] == 'transformer':
            return DataLoader(EquationDataset(test_equation_dataset['X'], test_equation_dataset['y']), batch_size=config['batch_size'], shuffle=False)
        elif config['model_type'] == 'decoder':
            # 注意：纯解码器测试时，每个 prompt 长度不同且不使用 padding，因此强行设定 batch_size=1
            return DataLoader(DecoderEquationDataset(test_equation_dataset['X'], test_equation_dataset['y'], config, is_test=True), batch_size=1, shuffle=False)
    return None

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

base_config = {
    "task": 'SubTask_2', # SubTask_1 (加法) 或 SubTask_2 (语言模型)
    "exp_name": 'subtask2_experiment_2',
    'train_digit_configs': [(3,3),(4,5),(5,5),(5,4)],
    'train_examples': 8000,
    'test_digit_configs': [(3,4),(4,3),(4,4)],
    'test_examples': 1000,
    "model_type": "decoder", # 若跑 SubTask_2 务必改为 'decoder'
    "model_dim": 100,
    "tokenizer_type": "subword", # 可选: 'word' 或 'subword'
    "use_glove": True,
    "glove_path": "/content/drive/MyDrive/pytorch_beginner/task2/glove/glove.6B.100d.txt",
    "freeze_embedding": False,
    "num_heads": 2,
    "num_encoders": 1,
    "num_decoders": 1,
    "layer_num": 6,
    "dropout": 0.1,
    "dim_feedforward": 256,
    "max_seq_len": 128, # 若跑 SubTask_2 建议调至 128
    "optimizer": "Adam",
    "lr": 5e-4,
    "batch_size": 32,
    "num_epochs": 50,
    "patience": 5,
    "max_gen_len": 10,
    "min_freq": 2,
}

train_loader, dev_loader = build_dataloaders(base_config)


accumulator = metrics_accumulator(6)
# 注意：入参剥离了外部的准确率函数
trainer = UniversalTrainer(base_config, device, accumulator)

print(f"=== 开始训练 {base_config['task']} ===")
best_loss, best_weights = trainer.train_and_evaluate(base_config['num_epochs'], train_loader, dev_loader)

@torch.no_grad()
def evaluate_and_plot_heatmap(model, config, device, digit_configs=[(3,3),(4,5),(5,5),(5,4),(3,4),(4,3),(4,4)]):
    model.eval()
    results = np.zeros((6, 6)) # 假设最大支持 5+5 位数，构建 6x6 矩阵（索引0不用）
    counts = np.zeros((6, 6))

    print("=== 生成示例输出 ===")
    # 针对每种配置生成 200 个测试样本
    for (len_a, len_b) in digit_configs:
        test_df = generate_addition_samples(digit_configs=[(len_a, len_b)], num_examples=200)

        # 组装 DataLoader
        if config['model_type'] == 'transformer':
            test_dataset = EquationDataset(test_df['X'], test_df['y'])
        else:
            test_dataset = DecoderEquationDataset(test_df['X'], test_df['y'], config, is_test=True)

        test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False)

        correct = 0
        for idx, batch in enumerate(test_loader):
            inputs, labels = batch
            inputs = {k: v.to(device) for k, v in inputs.items()}
            labels = labels.to(device)

            bgn_id, end_id = config['bgn_id'], config.get('end_id', 2)

            if config['model_type'] == 'transformer':
                preds = model.generate(inputs['src'], bgn_id, config['max_gen_len'])[:, 1:]
                pred_seq, true_seq = preds[0].tolist(), labels[0].tolist()
            else:
                prompt_len = inputs['x'].size(1)
                preds = model.generate(inputs['x'], config['max_gen_len'])
                pred_seq, true_seq = preds[0, prompt_len:].tolist(), labels[0].tolist()

            if end_id in pred_seq: pred_seq = pred_seq[:pred_seq.index(end_id)]
            if end_id in true_seq: true_seq = true_seq[:true_seq.index(end_id)]

            is_correct = (pred_seq == true_seq)
            if is_correct: correct += 1

            # 打印每个长度组合的前 1 个示例
            if idx == 0:
                x_str = test_df['X'].iloc[0]
                y_true_str = test_df['y'].iloc[0][::-1] # 还原真实字符串
                y_pred_str = "".join([id2char.get(i, "?") for i in pred_seq])[::-1] # 当前是反向预测，所以反转回来阅读
                mark = "✅" if is_correct else "❌"
                print(f"[{len_a}位数 + {len_b}位数] 输入: {x_str} | 预测: {y_pred_str} | 真实: {y_true_str} {mark}")

        accuracy = correct / 200.0
        results[len_a, len_b] = accuracy
        counts[len_a, len_b] = 1

    # 绘制热力图 (对齐 Animator 风格)
    plt.style.use('default')
    plt.rcParams['font.family'] = 'serif'
    plt.rcParams['font.serif'] = ['Times New Roman'] + plt.rcParams['font.serif']
    plt.rcParams['figure.dpi'] = 300
    backend_inline.set_matplotlib_formats("svg")

    fig, ax = plt.subplots(figsize=(6, 5))
    # 截取有数据的区域 (3到5)
    subset_results = results[3:6, 3:6]

    sns.heatmap(subset_results, annot=True, fmt=".1%", cmap="Blues",
                xticklabels=[3, 4, 5], yticklabels=[3, 4, 5],
                cbar_kws={'label': 'Exact Match Accuracy'}, ax=ax, vmin=0, vmax=1)

    ax.set_xlabel("Number of Digits in Operand B", fontsize=11)
    ax.set_ylabel("Number of Digits in Operand A", fontsize=11)
    ax.set_title(f"Addition Accuracy Heatmap ({config['model_type'].upper()})", fontsize=12)
    plt.tight_layout()
    plt.show()
    exp_name = config.get('exp_name', 'heatmap_experiment')
    save_path = f"/content/drive/MyDrive/pytorch_beginner/task3/{exp_name}_heatmap.pdf"
    fig.savefig(save_path, format='pdf', bbox_inches='tight')
    print(f"[*] 热力图已保存至: {save_path}")

evaluate_and_plot_heatmap(trainer.model, base_config, device)

def plot_architecture_comparison(csv_transformer, csv_decoder):
    import os
    if not os.path.exists(csv_transformer) or not os.path.exists(csv_decoder):
        print("错误：找不到指定的 CSV 文件，请确保两个实验都已运行并保存了 metrics。")
        return

    df_trans = pd.DataFrame(pd.read_csv(csv_transformer))
    df_dec = pd.DataFrame(pd.read_csv(csv_decoder))

    plt.style.use('default')
    plt.rcParams['font.family'] = 'serif'
    plt.rcParams['font.serif'] = ['Times New Roman'] + plt.rcParams['font.serif']
    plt.rcParams['figure.dpi'] = 300
    backend_inline.set_matplotlib_formats("svg")

    fig, ax = plt.subplots(figsize=(7, 4.5))

    # 绘制 Transformer 曲线
    ax.plot(df_trans['Epoch'], df_trans['Dev_Exact_Match'],
            label='Encoder-Decoder (Transformer)', color='#1f77b4', linestyle='-', linewidth=2)

    # 绘制 Decoder-Only 曲线
    ax.plot(df_dec['Epoch'], df_dec['Dev_Exact_Match'],
            label='Decoder-Only (GPT-style)', color='#d62728', linestyle='-', linewidth=2)

    ax.set_xlabel('Training Epochs', fontsize=11)
    ax.set_ylabel('Validation Exact Match Rate', fontsize=11)
    ax.set_title('Convergence Speed Comparison on Addition Task', fontsize=12)

    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.grid(True, linestyle='--', alpha=0.5)
    ax.legend(frameon=False, fontsize=10, loc='lower right')

    plt.tight_layout()
    plt.show()
    save_path = f"/content/drive/MyDrive/pytorch_beginner/task3/subtask1_model_comparison.pdf"
    fig.savefig(save_path, format='pdf', bbox_inches='tight')

plot_architecture_comparison(
     "/content/drive/MyDrive/pytorch_beginner/task3/subtask1_transformer_experiment_interpo_metrics.csv",
     "/content/drive/MyDrive/pytorch_beginner/task3/subtask1_decoder_experiment_interpolation_metrics.csv"
 )