# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pJfQ8CL2vVziczJMkkPNUPkgrQWjX5-f
"""

import pandas as pd
import numpy as np
import torch
import seaborn as sns
import matplotlib.pyplot as plt
from IPython import display
from matplotlib_inline import backend_inline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import CountVectorizer
from google.colab import drive
drive.mount('/content/drive')

"""## 数据预处理"""

tokenize_type = "(1,3)_gram"
if tokenize_type == "bag_of_word":
    vectorizer = CountVectorizer(min_df = 3)
elif tokenize_type == "(1,2)_gram":
    vectorizer = CountVectorizer(ngram_range = (1,2), min_df = 3)
elif tokenize_type == "(1,3)_gram":
    vectorizer = CountVectorizer(ngram_range = (1,3), min_df = 3)
else:
  raise ValueError('Invalid tokenize type')

train_data  = pd.read_csv("/content/drive/MyDrive/pytorch_beginner/task2/new_train.tsv", sep = "\t", header = None)
test_data  = pd.read_csv("/content/drive/MyDrive/pytorch_beginner/task2/new_test.tsv", sep = "\t", header = None)
train_data.columns = ["text", "label"]
test_data.columns = ["text", "label"]
X_train, X_dev, Y_train, Y_dev = train_test_split(train_data['text'], train_data[['label']], test_size = 0.2, random_state = 42)

#OneHotEncoder接受df输入，而CountVectorizer接受一维输入
enc = OneHotEncoder(handle_unknown = "ignore", sparse_output = False)
X_train_vec = vectorizer.fit_transform(X_train)
Y_train_vec = enc.fit_transform(Y_train)
Y_train_vec = torch.tensor(Y_train_vec, dtype = torch.float32)

X_dev_vec = vectorizer.transform(X_dev)
Y_dev_vec = enc.transform(Y_dev)
Y_dev_vec = torch.tensor(Y_dev_vec,dtype = torch.float32)

X_test = vectorizer.transform(test_data['text'])
Y_test = enc.transform(test_data[['label']])
Y_test_vec = torch.tensor(Y_test,dtype = torch.long)

X_train.apply(lambda x: len(x.split())).describe()

def x_plot_hist(X_train):
  lengths = X_train.apply(lambda x: len(x.split()))

  # 1. 全局字体与分辨率设置
  plt.style.use('default')
  plt.rcParams['font.family'] = 'serif'
  plt.rcParams['font.serif'] = ['Times New Roman'] + plt.rcParams['font.serif']
  plt.rcParams['figure.dpi'] = 300
  plt.rcParams['savefig.dpi'] = 300

  # 2. 创建画布
  fig, ax = plt.subplots(figsize=(6, 4))

  # 3. 绘制直方图
  # 颜色保持之前的灰蓝色，alpha设为0.9增加质感，edgecolor区隔不同的bin
  bars = ax.hist(lengths, bins=40, color='#4A708B', edgecolor='black',
                linewidth=0.6, alpha=0.9, zorder=3)

  # 4. 坐标轴与网格线优化
  ax.spines['top'].set_visible(False)
  ax.spines['right'].set_visible(False)
  ax.spines['bottom'].set_linewidth(0.8)
  ax.spines['left'].set_linewidth(0.8)

  # 底层虚线网格
  ax.grid(axis='y', linestyle='--', alpha=0.6, zorder=0)

  # 5. 标签设置
  ax.set_xlabel("Sentence Length (Number of Words)", fontsize=12, labelpad=8)
  ax.set_ylabel("Frequency", fontsize=12, labelpad=8)
  ax.tick_params(axis='both', labelsize=10)

  # 6. 学术加分项：添加 95% 分位数辅助线
  percentile_95 = np.percentile(lengths, 95)
  median_val = np.median(lengths)

  # 画一条深红色的虚线代表 95% 分位数截断点
  ax.axvline(percentile_95, color='#d62728', linestyle='--', linewidth=1.5, zorder=4)
  # 画一条灰色的虚线代表中位数
  ax.axvline(median_val, color='dimgray', linestyle=':', linewidth=1.5, zorder=4)

  # 添加文字标注
  ax.text(percentile_95 + 1, ax.get_ylim()[1] * 0.9,
          f'95th Percentile: {int(percentile_95)}',
          color='#d62728', fontsize=10, va='top')
  ax.text(median_val + 1, ax.get_ylim()[1] * 0.8,
          f'Median: {int(median_val)}',
          color='dimgray', fontsize=10, va='top')

  # 7. 紧凑布局并展示
  plt.tight_layout()
  #plt.savefig('/content/drive/MyDrive/pytorch_beginner/task1/length_distribution.pdf', format='pdf', bbox_inches='tight')
  plt.show()

def label_plot_bar(Y_train):
    counts = Y_train['label'].value_counts().sort_index()
    # 1. 全局字体与分辨率设置
    plt.style.use('default')
    plt.rcParams['font.family'] = 'serif'
    # 优先使用 Times New Roman，与多数 LaTeX 模板的正文体一致
    plt.rcParams['font.serif'] = ['Times New Roman'] + plt.rcParams['font.serif']
    # 设置高分辨率，保证导出图片放入 PDF 时不模糊
    plt.rcParams['figure.dpi'] = 300
    plt.rcParams['savefig.dpi'] = 300

    # 2. 创建画布
    fig, ax = plt.subplots(figsize=(6, 4))

    # 3. 颜色选择
    bar_color = '#4A708B'

    # 4. 绘制柱状图 (添加黑色边框增加锐利度，zorder=3保证柱子在网格线之上)
    bars = ax.bar(counts.index, counts.values,
                  color=bar_color, edgecolor='black', linewidth=0.8,
                  width=0.6, zorder=3)

    # 5. 坐标轴与网格线优化
    # 隐藏顶部和右侧的边框线（Spines）
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    # 弱化左侧和底部的边框线
    ax.spines['bottom'].set_linewidth(0.8)
    ax.spines['left'].set_linewidth(0.8)

    # 添加水平网格线，置于底层(zorder=0)，使用虚线和半透明度
    ax.grid(axis='y', linestyle='--', alpha=0.6, zorder=0)

    # 6. 标签与刻度设置
    ax.set_xticks(counts.index)
    ax.set_xticklabels(['0 (Negative)', '1', '2 (Neutral)', '3', '4 (Positive)'], fontsize=10)
    ax.set_xlabel("Sentiment Label", fontsize=12, labelpad=8)
    ax.set_ylabel("Number of Samples", fontsize=12, labelpad=8)

    # 7. 在柱子上方标注具体数值
    for bar in bars:
        height = bar.get_height()
        ax.annotate(f'{height}',
                    xy=(bar.get_x() + bar.get_width() / 2, height),
                    xytext=(0, 4),  # 垂直向上偏移4个像素
                    textcoords="offset points",
                    ha='center', va='bottom', fontsize=10)

    # 8. 紧凑布局并展示/保存
    plt.tight_layout()
    #plt.savefig('/content/drive/MyDrive/pytorch_beginner/task1/label_distribution.pdf', format='pdf', bbox_inches='tight')
    plt.show()

feature_names = vectorizer.get_feature_names_out()

# 查看前 10 个特征
print(feature_names[:20])
X_train_vec

"""## 模型搭建"""

def batch_iter(train_data, train_label,batch_size):
    if not isinstance(train_label, torch.Tensor):
        train_label = torch.from_numpy(train_label.values)
    batch_num = train_data.shape[0]//batch_size
    idx = np.random.permutation(train_data.shape[0])
    for i in range(batch_num):
        lower_bound = i * batch_size
        upper_bound = min((i+1)*batch_size, train_data.shape[0])
        batch_idx = idx[lower_bound: upper_bound]
        batch_data = train_data[batch_idx, : ]
        if hasattr(batch_data, "toarray"):
            batch_data = torch.from_numpy(batch_data.toarray()).float()
        yield batch_data, train_label[batch_idx]

def softmax(x: torch.tensor) -> torch.tensor:
    """x: design matrix"""
    x_max = torch.max(x,axis = 1, keepdims = True).values
    x = x - x_max
    x_exp = torch.exp(x)
    partition = x_exp.sum(axis = 1, keepdims = True)
    return x_exp/partition

def cross_entropy_loss(y: torch.tensor, y_hat: torch.tensor)-> float:
    y = torch.argmax(y, axis = 1)
    e = -torch.log(y_hat[range(len(y_hat)), y] + 1e-7)
    return e.mean()

def mean_square_loss(y: torch.tensor, y_hat: torch.tensor)-> float:
    """带1/2的损失函数"""
    loss_per_sample = 0.5*torch.sum((y-y_hat)**2, dim =1)
    return torch.mean(loss_per_sample)

def calc_accuracy(y, y_hat):
    y = torch.argmax(y, axis = 1)
    y_hat = torch.argmax(y_hat, axis = 1)
    if y_hat.dtype != y.dtype:
        y_hat = y_hat.type(y.dtype)
    return torch.sum(y_hat==y)

class metrics_accumulator:
    def __init__(self, n):
        self.metrics = [0.0]*n

    def add(self,*args):
        self.metrics = [a + float(b) for a,b in zip(self.metrics, args)]

    def reset(self):
        self.metrics = [0.0] * len(self.metrics)

    def get_item(self, idx):
        return self.metrics[idx]

class Animator:
    def __init__(self, x_label='Epoch', legend=None, figsize=(6, 4)):
        if legend is None:
            legend = ['Train Loss', 'Train Acc', 'Dev Loss', 'Dev Acc']
        self.legend_labels = legend

        # 全局学术字体与分辨率设定
        plt.style.use('default')
        plt.rcParams['font.family'] = 'serif'
        plt.rcParams['font.serif'] = ['Times New Roman'] + plt.rcParams['font.serif']
        plt.rcParams['figure.dpi'] = 300

        # 修复 DeprecationWarning，使用最新的矢量图设置方法
        backend_inline.set_matplotlib_formats("svg")
        self.fig, self.ax1 = plt.subplots(figsize=figsize)
        self.ax2 = self.ax1.twinx()

        self.line_styles = [
            {'color': '#1f77b4', 'linestyle': '-',  'linewidth': 1.5}, # Train Loss
            {'color': '#d62728', 'linestyle': '-',  'linewidth': 1.5}, # Train Acc
            {'color': '#1f77b4', 'linestyle': '--', 'linewidth': 1.5}, # Dev Loss
            {'color': '#d62728', 'linestyle': '--', 'linewidth': 1.5}  # Dev Acc
        ]

        def config_axes():
            self.ax1.set_xlabel(x_label, fontsize=11)

            # 强制右侧坐标轴保持在右侧
            self.ax2.yaxis.tick_right()
            self.ax2.yaxis.set_label_position("right")

            self.ax1.set_ylabel('Cross Entropy Loss', fontsize=11, color='#1f77b4')
            self.ax2.set_ylabel('Accuracy', fontsize=11, color='#d62728')

            self.ax1.tick_params(axis='y', labelcolor='#1f77b4')
            self.ax2.tick_params(axis='y', labelcolor='#d62728')

            self.ax1.spines['top'].set_visible(False)
            self.ax2.spines['top'].set_visible(False)
            self.ax1.spines['left'].set_color('#1f77b4')
            self.ax2.spines['right'].set_color('#d62728')

            self.ax1.grid(True, linestyle='--', alpha=0.5, zorder=0)

        self.config_axes = config_axes
        # 确保初始化了数据存储器 (解决 AttributeError 的核心)
        self.X, self.Y = None, None

    def add(self, x, y):
        if not hasattr(y, "__len__"):
            y = [y]
        n = len(y)
        if not hasattr(x, "__len__"):
            x = [x] * n
        if not self.X:
            self.X = [[] for _ in range(n)]
        if not self.Y:
            self.Y = [[] for _ in range(n)]

        for i, (a, b) in enumerate(zip(x, y)):
            if a is not None and b is not None:
                self.X[i].append(a)
                self.Y[i].append(b)

        self.ax1.cla()
        self.ax2.cla()

        lines = []
        for i, (x_data, y_data) in enumerate(zip(self.X, self.Y)):
            style = self.line_styles[i % len(self.line_styles)]
            if i % 2 == 0:
                line, = self.ax1.plot(x_data, y_data, **style, zorder=3)
            else:
                line, = self.ax2.plot(x_data, y_data, **style, zorder=3)
            lines.append(line)

        self.config_axes()

        if self.legend_labels:
            self.ax1.legend(lines, self.legend_labels, frameon=False,
                            fontsize=9, loc='center right', bbox_to_anchor=(0.95, 0.5))

        plt.tight_layout()
        display.display(self.fig)
        display.clear_output(wait=True)

    def save_fig(self, filename):
        self.fig.savefig(filename, format='pdf', bbox_inches='tight')

class SoftmaxRegression:
    def __init__(self, W, b):

        self.W = W
        self.b = b

    def forward(self, batch):
        if not isinstance(batch, torch.Tensor):
            if hasattr(batch, "toarray"):
                batch = torch.from_numpy(batch.toarray()).float()
        return softmax(torch.matmul(batch, self.W) + self.b)

    def update(self, X, y_hat, y, lr: float, loss_type = 'ce', weight_decay = None):
        """
        loss_type: "ce" (Cross Entropy) 或 "mse"
        """
        if loss_type == 'ce':
          dZ = y_hat - y
        elif loss_type == 'mse':
          diff = y_hat - y
          term1 = y_hat*diff
          term2 = y_hat*torch.sum(term1,axis = 1,keepdims=True)
          dZ = term1 - term2
        else:
          raise ValueError("Unsupported loss type")
        m = X.shape[0]
        dW = torch.matmul(X.T, dZ) / m
        if weight_decay:
          dW += weight_decay*self.W
        db = torch.sum(dZ, axis=0) / m
        self.W = self.W - lr * dW
        self.b = self.b - lr * db

"""## 超参数设置与初始化"""

batch_size = 20
num_epochs = 50
lr = 0.5
vocab_size = X_train_vec.shape[1]
num_classes = Y_train_vec.shape[1]
W = torch.randn((vocab_size, num_classes), dtype = torch.float32) * 0.01
b = torch.zeros(num_classes, dtype = torch.float32)
#b = torch.tensor([20.0, 0.0, 0.0, 0.0, 0.0], dtype=torch.float32)
model = SoftmaxRegression(W, b)
metrics = metrics_accumulator(6)
best_dev_loss = float('inf')
animator = Animator()

"""## 模型训练"""

animator = Animator()
for epoch in range(num_epochs):
    metrics.reset()
    for X, y in batch_iter(X_train_vec, Y_train_vec, batch_size):
        y_hat = model.forward(X)
        loss = cross_entropy_loss(y, y_hat)
        model.update(X, y_hat, y, lr, loss_type = 'ce', weight_decay = None)
        metrics.add(loss*y.shape[0], calc_accuracy(y,y_hat), y.shape[0],0,0,0)

    for X_dev, y_dev in batch_iter(X_dev_vec, Y_dev_vec, batch_size):
        y_dev_hat = model.forward(X_dev)
        dev_loss = cross_entropy_loss(y_dev, y_dev_hat)
        metrics.add(0,0,0,dev_loss*y_dev.shape[0], calc_accuracy(y_dev,y_dev_hat), y_dev.shape[0])

    train_loss = metrics.get_item(0)/metrics.get_item(2)
    train_acc = metrics.get_item(1)/metrics.get_item(2)
    dev_loss = metrics.get_item(3)/metrics.get_item(5)
    dev_acc = metrics.get_item(4)/metrics.get_item(5)
    animator.add(epoch + 1, (train_loss, train_acc, dev_loss, dev_acc))
    if dev_loss < best_dev_loss:
        best_dev_loss = dev_loss
        best_W = model.W.clone()
        best_b = model.b.clone()

pic_save_path = '/content/drive/MyDrive/pytorch_beginner/task1/Trigram_5e-1'
animator.save_fig(pic_save_path)

"""## 模型预测"""

class F1MacroAccumulator:
    def __init__(self, num_classes=5):
        self.num_classes = num_classes
        self.TP = torch.zeros(num_classes, dtype=torch.float32)
        self.FP = torch.zeros(num_classes, dtype=torch.float32)
        self.FN = torch.zeros(num_classes, dtype=torch.float32)

    def add_batch(self, y_true, y_pred):
        """
        y_true: shape (batch_size, num_classes) 或 (batch_size,)
        y_pred: shape (batch_size, num_classes)
        """
        if y_true.ndim > 1:
            y_true = torch.argmax(y_true, dim=1)
        if y_pred.ndim > 1:
            y_pred = torch.argmax(y_pred, dim=1)

        for i in range(self.num_classes):
            true_i = (y_true == i)
            pred_i = (y_pred == i)

            self.TP[i] += torch.sum(true_i & pred_i)
            self.FP[i] += torch.sum((~true_i) & pred_i)
            self.FN[i] += torch.sum(true_i & (~pred_i))

    def get_macro_f1(self) -> float:
        epsilon = 1e-7
        precision = self.TP / (self.TP + self.FP + epsilon)
        recall = self.TP / (self.TP + self.FN + epsilon)

        f1_per_class = 2 * (precision * recall) / (precision + recall + epsilon)

        # 返回所有类别 F1 的算术平均值
        return torch.mean(f1_per_class).item()

model.W = best_W
model.b = best_b

# 在测试集上进行最终评估
f1MacroAccumulator = F1MacroAccumulator(num_classes = 5)
test_loss_sum = 0
correct_samples = 0
total_samples = 0
for x_test, y_test in batch_iter(X_test, Y_test_vec, batch_size):
  y_test_hat = model.forward(x_test)
  test_loss = cross_entropy_loss(y_test, y_test_hat)
  f1MacroAccumulator.add_batch(y_test, y_test_hat)
  test_loss_sum += test_loss*y_test.shape[0]
  correct_samples += calc_accuracy(y_test,y_test_hat)
  total_samples += y_test.shape[0]

print(f"Best Dev Loss: {best_dev_loss:.4f}")
print(f"Test Loss: {test_loss_sum/total_samples:.4f}")
print(f"Final Test Accuracy: {correct_samples/total_samples:.4f}")
print(f"Final F1 Macro: {f1MacroAccumulator.get_macro_f1():.4f}")